[project]
name = "ml-service"
version = "0.1.0"
description = ""
authors = [
    {name = "vito_brat",email = "bratko.viktor2004@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "pydantic (>=2.12.5,<3.0.0)",
    "omegaconf (>=2.3.0,<3.0.0)",
    "pydantic-settings (>=2.13.1,<3.0.0)",
    "uvicorn (>=0.41.0,<0.42.0)",
    "fastapi (>=0.135.1,<0.136.0)",
    "slowapi (>=0.1.9,<0.2.0)",
    "pre-commit (>=4.5.1,<5.0.0)",
    "qdrant-client (>=1.14.2,<2.0.0)",
    "tritonclient[grpc] (>=2.66.0,<3.0.0)",
    "numpy (>=2.4.3,<3.0.0)",
    "aio-pika (>=9.6.1,<10.0.0)",
    "dependency-injector (>=4.48.3,<5.0.0)",
    "python-json-logger (>=4.0.0,<5.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-asyncio (>=1.3.0,<2.0.0)",
    "testcontainers[qdrant] (>=4.14.1,<5.0.0)",
    "transformers (>=5.3.0,<6.0.0)"
]


[project.optional-dependencies]
test = [
    "pytest>=9.0.0",
    "pytest-asyncio>=0.25.0",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
