app_host: "0.0.0.0"
app_port: 8888
log_level: "DEBUG"
workers_number: 1

qdrant:
  host: "qdrant"
  port: 6333
  grpc_port: 6334
  collection_name: "documents"
  hnsw_edge_size: 16
  hnsw_neighbour_size: 100

triton:
  host: "triton"
  grpc_port: 8001
  http_port: 8000

rabbitmq:
  host: "rabbitmq"
  port: 5672
  vhost: "ml"
